global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.yaml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['pg-exporter:9187']
